# $Id: Makefile 2503 2007-07-24 09:25:41Z henningw $
#
# cfgutils module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=cfgutils.so
LIBS=

include ../../Makefile.modules

