# $Id: Makefile 830 2006-05-13 08:49:58Z bogdan_iancu $
#
# rr module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=rr.so
LIBS=

#DEFS+=-DENABLE_USER_CHECK

include ../../Makefile.modules
