# $Id: Makefile 2151 2007-05-04 15:55:26Z miconda $
#
# Digest Authentication - Diameter support
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs

auto_gen=
NAME=auth_diameter.so

include ../../Makefile.modules
