# $Id: Makefile 1107 2006-09-19 08:32:47Z bogdan_iancu $
#
# registrar module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=registrar.so
LIBS=

include ../../Makefile.modules
