# $Id: Makefile 1448 2006-12-22 17:07:44Z eliasbaixas $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=seas.so
LIBS=

include ../../Makefile.modules
