# $Id: Makefile 31 2005-06-16 13:08:32Z bogdan_iancu $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=uac.so
LIBS= 

include ../../Makefile.modules
