# $Id: Makefile 717 2006-03-03 21:01:12Z agranig $
#
# path module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=path.so
LIBS=

include ../../Makefile.modules
