# $Id: Makefile 787 2006-04-07 09:43:28Z miconda $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=siptrace.so
LIBS=

include ../../Makefile.modules
