# $Id: Makefile 1154 2006-10-06 13:53:56Z anca_vamanu $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

include ../../Makefile.defs
auto_gen=
NAME=imc.so
LIBS=

include ../../Makefile.modules
