# $Id: Makefile 2 2005-06-13 16:47:24Z bogdan_iancu $
#
# database example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

auto_gen=
NAME=dbexample.so
LIBS=

include ../../Makefile.modules
