# $Id: Makefile 2 2005-06-13 16:47:24Z bogdan_iancu $
#
# example module makefile
#
# 
# WARNING: do not run this directly, it should be run by the master Makefile

# extra debug messages
DEFS+=-DDBT_EXTRA_DEBUG
 
include ../../Makefile.defs
auto_gen=
NAME=dbtext.so
LIBS=

include ../../Makefile.modules
